import Head from "next/head"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Image from "next/image"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Next Events</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header>
				<nav>
					{/* <img /> */}
					<Link href={"/"} passHref legacyBehavior>
						<a>Home</a>
					</Link>
					<Link href="/events" passHref legacyBehavior>
						<a>Events</a>
					</Link>
					<Link href="/about" passHref legacyBehavior>
						<a>About</a>
					</Link>
				</nav>
			</header>

			<main className={`${styles.main} ${inter.className}`}>
				Hello! Welcome to Next Events!
				{data.map((evt) => (
					<Link key={evt.id} href={`/events/${evt.id}`} passHref legacyBehavior>
						<a>
							<Image
								src={evt.image}
								width={"100"}
								height={"100"}
								alt="event thumbnail"
							/>
							<h2>{evt.title}</h2>
							<p>{evt.description}</p>
						</a>
					</Link>
				))}
			</main>
		</>
	)
}

export async function getServerSideProps() {
	const { events_categories } = await import("/data/data.json")

	return {
		props: {
			data: events_categories,
		},
	}
}
