import Head from "next/head"
import { Inter } from "next/font/google"
import styles from "@/styles/Home.module.css"
import Image from "next/image"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ data }) {
	return (
		<>
			<Head>
				<title>Next Events</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header>
				<nav>
					{/* <img /> */}
					<a href="/">Home</a>
					<a href="/events">Events</a>
					<a href="/about">About</a>
				</nav>
			</header>

			<main className={`${styles.main} ${inter.className}`}>
				Hello! Welcome to Next Events!
				{data.map((evt) => (
					<a key={evt.id} href="">
						<Image
							src={evt.image}
							width={"100"}
							height={"100"}
							alt="event thumbnail"
						/>
						<h2>{evt.title}</h2>
						<p>{evt.description}</p>
					</a>
				))}
			</main>
		</>
	)
}

export async function getServerSideProps() {
	const { events_categories } = await import("/data/data.json")

	return {
		props: {
			data: events_categories,
		},
	}
}

// export function getServerSideProps() {
// 	return {
// 		props: {
// 			name: "John",
// 		},
// 	}
// }
